stages:
  describe:
    cmd: python3 starts.py Stars.csv
    deps:
    - Stars.csv
    - starts.py
    outs:
    - metastar.json
  createDatapackage:
    cmd: python3 stardatapackage.py Stars.csv
    deps:
    - Stars.csv
    - stardatapackage.py
    outs:
    - datapackage.json
